
- name: Install IIS Web-Server with sub features and management tools
  win_feature:
    name: Web-Server
    state: present
    restart: True
    #include_sub_features: True
    #include_management_tools: True

- name: Generate Self Sign CSR Request
  raw: New-SelfSignedCertificate -certstorelocation cert:\localmachine\my -dnsname {{ inventory_hostname }}.lab.rhlabs.net | select Thumbprint | ft -HideTableHeaders
  register: csr

- debug:
    msg: "{{ csr.stdout | trim  }}"

- name: Remove Default Web Site
  win_iis_website:
    name: "Default Web Site"
    state: absent

- name: Create directory structure
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - C:\sites
    - C:\sites\Demo
    - C:\sites\logs

- name: Create Demo IIS site
  win_iis_website:
    name: Demo
    state: started
    physical_path: c:\sites\Demo
    parameters: logfile.directory:c:\sites\logs
    ssl: True
  register: website

- debug:
    msg: "{{ website }}"

- name: Add HTTPS Webbinding to IIS
  win_iis_webbinding:
    name: Demo
    protocol: https
    certificate_hash: "{{ csr.stdout | trim }}"
    state: present

- name: Remove the HTTP binding on port 80
  win_iis_webbinding:
    name: Demo
    port: 80
    state: absent

- name: Create directory structure
  win_template:
    src: template/index.html.j2
    dest: c:\sites\Demo\index.html
