---
- name: "Deploy new VM called {{ item.vm_name }}"
  vmware_guest:
    datacenter: "{{ vmware_datacenter }}"
    cluster: "{{ vmware_cluster }}"
    resource_pool: "{{ vmware_resource_pool }}"
    name: "{{ item.vm_name }}"
    template: "{{ vmware_template_name }}"
    linked_clone: "{{ vmware_linked_clone }}"
    wait_for_ip_address: no
    folder: "{{ vmware_folder }}"
    state: "{{ vmware_state }}"

    disk:
    - size_gb: "{{ vmware_disk_size }}"
      type: thin
      datastore: "{{ vmware_datastore }}"

    hardware:
      memory_mb: "{{ vmware_ram_mb }}"
      num_cpus: "{{ vm_cpu_count }}"

    networks:
    - name: "{{ vmware_network }}"
      ip: "{{ item.vm_ip }}"
      netmask: "{{ item.vm_mask }}"
      gateway: "{{ item.vm_gw }}"
      start_connected: "{{ vmware_net_start_connected }}"

  with_items:  "{{ vmware_new_machines }}"
  delegate_to: localhost
  changed_when: False

