---
# defaults file for kev-vmware-provision/---

vmware_datacenter: 'KEV Datacenter'
vmware_cluster: 'KEV Cluster'
vmware_resource_pool: WindowsLab
vmware_template_name: TEMPLATE-Windows2016
vmware_datastore: VMNFS
vmware_folder: '/'
vmware_disk_size: 50
vmware_ram_mb: 2048
vm_cpu_count: 1
vm_core_per_cpu: 1
vmware_network: VLAN20
vmware_state: poweredon
vmware_net_start_connected: True
vmware_linked_clone: False

vmware_new_machines:
  - vm_name: WindowsLab01
    vm_ip: NULL
    vm_mask: NULL
