---
- name: "Deploy new VM called {{ vmware_new_hostname }} with {{ vm_cpu_count }} CPUs, {{ vmware_disk_size }} HDD, {{ vmware_ram_mb }} RAM with {{ vmware_network }} network from {{ vmware_template_name }} template."
  vmware_guest:
    datacenter: "{{ vmware_datacenter }}"
    name: "{{ vmware_new_hostname }}"
    template: "{{ vmware_template_name }}"
    wait_for_ip_address: yes
    folder: "{{ vmware_folder }}"
    state: "{{ vmware_state }}"

    disk:
    - size_gb: "{{ vmware_disk_size }}"
      type: thin
      datastore: "{{ vmware_datastore }}"

    hardware:
      memory_mb: "{{ vmware_ram_mb }}"
      num_cpus: "{{ vm_cpu_count }}"

    networks:
    - name: "{{ vmware_network }}"
      ip: "{{ vmware_manual_ip }}"
      netmask: "{{ vmware_manual_netmask }}"
      mac: "{{ vmware_manual_mac }}"

#      mac: "{{ vmware_manual_mac | default(omit) }}"

  register: newvminfo
  delegate_to: localhost
  changed_when: False

- name: debug newvminfo raw
  debug:
    msg: "New IP address is {{ newvminfo }}"
  when: newvminfo is defined
  ignore_errors: true

- name: debug newvminfo.instance.ipv4
  debug:
    msg: "New IP address is {{ newvminfo.instance.ipv4 }}"
  when: newvminfo.instance.ipv4 is defined
  ignore_errors: true

- name: debug newvminfo.instance.ipv4
  debug:
    msg: "New UUID is {{ newvminfo.instance.hw_product_uuid }}"
  when: newvminfo.instance.hw_product_uuid is defined
  ignore_errors: true

- name: "Using set_stats to save info from the newly provisionined VM"
  set_stats:
    data:
      vmware_new_uuid: "{{ newvminfo.instance.hw_product_uuid }}"
      vmware_new_ip: "{{ newvminfo.instance.ipv4 }}"
      vmware_new_hostname: "{{ vmware_new_hostname }}"
    ignore_errors: true

- name: "add {{ newvminfo.instance.ipv4 }} host to group {{ new_vmware_inventory_group }}"
  add_host:
    name: "{{ newvminfo.instance.ipv4 }}"
    groups: "{{ new_vmware_inventory_group }}"
  changed_when: False

